/*
 * generated by Xtext
 */
package org.rjpower.iced.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class IcedCoffeeProposalProvider extends
    AbstractIcedCoffeeProposalProvider {
  @Override
  public void complete_ID(EObject model, RuleCall ruleCall,
      ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
    super.complete_ID(model, ruleCall, context, acceptor);
  }
}