/*
* generated by Xtext
*/
package org.rjpower.iced.ui.contentassist;

import org.rjpower.iced.ui.contentassist.AbstractIcedCoffeeProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IcedCoffeeProposalProvider extends AbstractIcedCoffeeProposalProvider {

}
