/*
 * generated by Xtext
 */
package org.rjpower.iced.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
import org.rjpower.iced.services.IcedCoffeeGrammarAccess;

public class IcedCoffeeFormatter extends AbstractDeclarativeFormatter {

  @Override
  protected void configureFormatting(FormattingConfig c) {
    IcedCoffeeGrammarAccess g = (IcedCoffeeGrammarAccess) getGrammarAccess();
    c.setLinewrap(0, 1, 2).before(g.getCOMMENTRule());
    c.setIndentationIncrement().after(g.getKW_FATARROWRule());
    c.setIndentationIncrement().after(g.getKW_THINARROWRule());
  }
}
