/*
 * generated by Xtext
 */
package org.rjpower.iced;


/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class IcedCoffeeRuntimeModule extends
    org.rjpower.iced.AbstractIcedCoffeeRuntimeModule {

  @Override
  public Class<? extends org.eclipse.xtext.parser.antlr.Lexer> bindLexer() {
    return Lexer.class;
  }

  @Override
  public void configureRuntimeLexer(com.google.inject.Binder binder) {
    binder
        .bind(org.eclipse.xtext.parser.antlr.Lexer.class)
        .annotatedWith(
            com.google.inject.name.Names
                .named(org.eclipse.xtext.parser.antlr.LexerBindings.RUNTIME))
        .to(Lexer.class);
  }
}
